config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "celebrities#index", as: "root"
  get "/celebrities/:id", to: "celebrities#show", as: "celebrity"
  post "/celebrities/", to: "celebrities#create"
  put "/celebrities/:id", to: "celebrities#update"
  patch "/celebrities/:id", to: "celebrities#update"
  delete "/celebrities/:id", to: "celebrities#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :setup_data

    @@celebrities = []

    #Show all celebrities
    def index
        # render plain: "This is the index"
    end

    #Show a single celebrity
    def show
        # render plain: "This is the show"

        @id = params["id"].to_i

    end

    #Create a new celebrity
    def create

        puts "New celebrity #{params}"

        new_celebrity = {
            name: params[:name],
            notability: params[:notability]
        }
        # session[:celebrities].push new_celebrity

        @celebrities.push new_celebrity

        puts "New celebrity #{ @celebrities }"

        # render plain: "New celebrity added"

    end

    #Update a celebrity
    def update
    end

    #Remove a celebrity
    def destroy
    end

    private
    def setup_data

        session[:celebrities] = [
            { name: "Lindsay Lohan", notability: "Parent Trap" },
            { name: "Adam Sandler", notability: "Big Daddy" },
            { name: "Rob Schnider", notability: "Adam Sandler" }
        ] unless session[:celebrities]

        @celebrities = session[:celebrities]

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/celebrities/create.html.erb
<h1>Landing page after creating a new celebrity</h1>

app/views/celebrities/index.html.erb
<%= render "shared/top_nav" %>

<h2>List of all the celebrities</h2>

<ul>
    <% for person in @celebrities %>

        <li>Celebrity <%= person["name"] %> has a notability of <%= person["notability"] %> </li>

    <% end %>
</ul>

app/views/celebrities/show.html.erb
<h2>Celebrity_id: <%= @id %></h2>

<% if @id <= @celebrities.length %>

    <ul>
        <li>Name: <%= @celebrities[@id]["name"] %></li>
        <li>Notability: <%= @celebrities[@id]["notability"] %></li>
    </ul>

<% else %>
    <p>Celebrity not found</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CelebritiesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_top_nav.html.erb
<ul>
    <% @celebrities.length.times do |idx| %>

        <li><%= link_to(@celebrities[idx]["name"], celebrity_path(idx)) %></li>

    <% end %>
</ul>